#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be: 1,2,3,5,8,13,21,34,55,89...,
#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#find the sum of the even-valued terms.


number_1 = 1
number_2 = 1
list = [number_1, number_2]

for fib in range(2, 11):
    number_3 = number_1 + number_2
    list.append(number_3)
    number_1 = number_2
    number_2 = number_3

Sum = sum(list)
print(Sum)
